#docker-compose.dev.yml
services:
  node-app:
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run start-dev
    ports:
      - "5000:3000"