#docker-compose.prod.yml
services:
  node-app:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - node-app